<?php

namespace App\Services\Actualizaciones\Enums;

enum CodigoMotivoActualizacion: string
{
    case GET_USUARIO = 'GET-USR';
    case GET_SUCURSALES = 'GET-SUC';
    case GET_ARTICULOS = 'GET-ART';
    case SET_NOTIFICACION_LOGIN = 'SET-LOG';
    case ENVIO_VENTA = 'ENV-VTS';
    case GET_DE_STOCK = 'GET-STK';
    case GET_LISTAS = 'GET-LST';
    case GET_DE_PERFILES = 'GET-PER';
    case GET_MOTIVOS_DE_DESCUENTO = 'GET-MTVDESC';
    case GET_ESTADO_MOVIMIENTO_CAJA = 'GET-ESTMOVCAJA';
    case GET_MOVIMIENTOS_DE_CAJA = 'GET-MOVCAJA';
    case GET_CAJA = 'GET-CAJA';
    case GET_MOTIVOS_DE_MOVIMIENTO = 'GET-MOTMOVCAJA';
    case GET_USUARIOS_SUCURSAL = 'GET-USRSUC';
    case GET_TRANSFERENCIAS_STOCK = 'GET-TRANSSTCK';
    case GET_USUARIOS_SUCURSAL_CAJA = 'GET-USRSUCCAJ';
    case GET_MODIFICACIONES_SOBRANTES = 'GET-MODSBRCAJA';
    case GET_ARTICULO_STOCK_VISIBLE = 'GET-ARTSTKVSB';
    case GET_ARTICULO_STOCK_VISIBLE_TOTAL = 'GET-ARTSTKVSB-TOT';
    case GET_PROVEEDORES = 'GET-PRV';
    case GET_IMPUESTOS = 'GET-IMPUESTOS';
    case GET_ANULACION_COMPRA = 'GET-ACOMPRA';
    case GET_PROMOCIONES = 'GET-PROMOCIONES';
    case GET_FERIADOS = 'GET-FERIADOS';
    case GET_COSTO_POR_SUCURSAL = 'GET-COST.PROV.SUC.';
    case GET_ANULACION_DE_VENTA = 'GET-ANLCN-VTA';
    case GET_CONFIGURACION_VISOR = 'GET-CF-VISOR';
    case GET_ARTICULO_PROMOCION_VER = 'GET-ART-PROM-VER';
    case GET_MODO_DE_COBRO = 'GET-MDO-COBRO';
    case GET_LETRAS = 'GET-LETRAS';
    case GET_PAGOS = 'GET-PAGOS';
    case GET_PRECIOS_TEMPORALES = 'GET-PRECIOS-TMP';
}
