<?php

namespace App\Services\AsyncProcess\Enums;

enum AvailableAsyncProcess: string
{

    case TEST = 'PROCESAR_TEST';

    /** PROCESAMIENTO DE COSTOS ** */
    case PROCESAR_COMPRA = 'PROCESAR_COMPRA';
    case ACTUALIZAR_REFERENCIAS_COSTOS = 'ACTUALIZAR_REFERENCIAS_COSTOS';
    case ACTUALIZAR_REFERENCIAS_COSTOS_POR_DETALLES = 'ACTUALIZAR_REFERENCIAS_COSTOS_POR_DETALLES';


    /** MERCADO PAGO ****/
    case MERCARDO_PAGO_PROCESAR_EVENTO = 'MERCARDO_PAGO_PROCESAR_EVENTO';
}
