<?php

namespace App\Services\AsyncProcess\Enums;

enum AvailableAsyncProcess: string
{

    case TEST = 'PROCESAR_TEST';

    /** PROCESAMIENTO DE COMPRAS ** */
    case PROCESAR_COMPRA = 'PROCESAR_COMPRA';
    case ACTUALIZAR_REFERENCIAS_COSTOS = 'ACTUALIZAR_REFERENCIAS_COSTOS';
    case ACTUALIZAR_REFERENCIAS_COSTOS_POR_DETALLES = 'ACTUALIZAR_REFERENCIAS_COSTOS_POR_DETALLES';

    case ANALIZAR_COMPRAS_DUDOSAS = 'ANALIZAR_COMPRAS_DUDOSAS';

    /** MERCADO PAGO ****/
    case MERCARDO_PAGO_PROCESAR_EVENTO = 'MERCARDO_PAGO_PROCESAR_EVENTO';

    /** VENTAS SUCURSALES **/
    case PROCESAR_VENTA_SUCURSAL = 'PROCESAR_VENTA_SUCURSAL';
}
